### ISSUE TITLE
corruption issue

### ISSUE THREAD

**Issue by ahmedibrahimx25** [PacktPublishing/Ultimate-Graphic-Design-Course-Create-40-Practical-Projects#2]
Files has a problem, the zipped files within the sections or outside wont open.

**Comment by Sonakshis** [comment]
Hi
You need to use GitHub Desktop to clone the repo since it uses Git LFS, so normal download as a zip from browser method would not work and would throw a corruption error. Once the files are cloned and downloaded, you will be able to view the files and the zip files can be extracted.
You can refer to the following document:
https://docs.github.com/en/repositories/working-with-files/managing-large-files/configuring-git-large-file-storage

We were able to download the resources using GitHub Desktop.
